### ISSUE TITLE
Added Readme file

### ISSUE THREAD

**Issue by lyiris22** [UBC-MDS/DSCI_522_wine-quality-predictors#18]
Hi, I had submitted the new readme file and moved the old readme file to docs folder. Could you please review it?

**Comment by reza-bagheri** [comment]
Yes I will take a look

**Comment by lyiris22** [comment]
Hi, I have submitted a new pull request, that fixed the comments in the scripts and modified the old proposal file. Could you please double check them?

**Comment by reza-bagheri** [comment]
Sure
