### ISSUE TITLE
Report feedback

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/DSCI_522_wine-quality-predictors#36]
- Would engage readers more if you said why answering this question was important or interesting
- There are A LOT of plots in your report... To make your report more readable, maybe just keep the most interesting/key ones (for example the analysis that you choose in the end as the "best" one) in the main part of the report and move the rest to the end and label it as an appendix? Keep table 2 in the main part as its a nice summary of what you did.
- What would you do next if you had more time to work on the project? I recommend adding that to the end of your discussion.

**Comment by reza-bagheri** [comment]
Thanks for the comments.
+ In the introduction part, a few lines were added to clarify the importance of the study.
+ Two appendices were added at the end of the report, and most of the pictures were moved there.
+ A 'conclusions' and a 'future work' section were added at the end of the report.
