### ISSUE TITLE
Making trees more readable

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/DSCI_522_wine-quality-predictors#37]
The text in some of decision tree graphic is far to small to be useful. Could simplify if by rotating it 90 degrees (more room for bigger text!) and including less info on the graphic (value, samples and gini could be in a table in an appendix).

**Comment by reza-bagheri** [comment]
Thanks for the comments.  The trees were rotated by 90 degrees, and we tried to remove the labels and the Gini index from the pictures. Of course, the library has some limitation, and we were not able to remove everything.
