### ISSUE TITLE
Final project modifications

### ISSUE THREAD

**Issue by lyiris22** [UBC-MDS/DSCI_522_wine-quality-predictors#41]
Hi @reza-bagheri , I had submitted a new pull request including:
- Code of Conduct
- Makefile Graph (Optional)
The readme is also modified according to the change of Dockerfile. Please take a look and merge if you think it's okay!

**Comment by reza-bagheri** [comment]
I just finished the final report and pushed it into my fork. There was a problem with the md file. It seems that github does not render my html tags properly. The pictures that placed side by side were misaligned and I was forced to turn them back into their original alignment. I added the appendix, a conclusion and a future work part, and moved most of the picture to the appendix. I am also going to modify the Readme file a little.

**Comment by reza-bagheri** [comment]
Just added a line to the Readme file to give some info on the importance a the project

**Comment by reza-bagheri** [comment]
I also replied to the comments. Please take a final look and let me know if you have any comments.

**Comment by lyiris22** [comment]
Thank you, I'll take a look!

**Comment by reza-bagheri** [comment]
Sure

**Comment by lyiris22** [comment]
Thanks, I just merged it. Could you check if our docker image works well on your local computer?

**Comment by reza-bagheri** [comment]
Looks fine.
