### ISSUE TITLE
Modified readme

### ISSUE THREAD

**Issue by lyiris22** [UBC-MDS/DSCI_522_wine-quality-predictors#6]
I had made some modification to the readme file to meet lab requirements and created a pull request. Would you please check it and see what we can improve? Thanks!

**Comment by reza-bagheri** [comment]
OK, I will take a look.

**Comment by reza-bagheri** [comment]
I have changed the folder structure, updated the README file and created a pull request.

**Comment by lyiris22** [comment]
Thanks, I reviewed it and merged the pull request.
